# -*- coding: utf-8 -*-
"""p_slr_d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QZLExxH7LDRFVfJBERfVWdnU2QGkseyQ
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df=pd.read_csv('Salary_dataset.csv')

X=df['Salary']
Y=df['YearsExperience']

import sklearn
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=99)

training_data=pd.DataFrame()

training_data['x_train_s']=x_train
training_data['y_train_s']=y_train
training_data

testing_data=pd.DataFrame()
testing_data['x_test_s']=x_test
testing_data['y_test_s']=y_test
testing_data

from sklearn.linear_model import LinearRegression

reg=LinearRegression()

x_train=x_train.values.reshape(-1,1)

reg.fit(x_train,y_train)

reg.coef_

reg.intercept_

y_train_predict=reg.predict(x_train)
y_train_predict

training_data['y_train_predict_s']=y_train_predict
training_data

from sklearn.metrics import r2_score
r2_score(y_train,y_train_predict)

plt.figure(figsize=(5,3))
plt.title('Training data')
plt.xlabel('x_train_values')
plt.ylabel('y_train_values')
plt.scatter(x=x_train,y=y_train)
plt.plot(x_train,y_train_predict,color='g',marker='*')
plt.show()

from sklearn.metrics  import mean_squared_error
mean_squared_error(y_train,y_train_predict)

testing_data

x_test=x_test.values.reshape(-1,1)

y_test_predict=reg.predict(x_test)
y_test_predict

testing_data['y_test_predict_s']=y_test_predict
testing_data

from sklearn.metrics import r2_score
r2_score(y_test,y_test_predict)

mean_squared_error(y_test,y_test_predict)

plt.figure(figsize=(5,3))
plt.title('Testing data')
plt.xlabel('x_test_values')
plt.ylabel('y_test_values')
plt.scatter(x=x_test,y=y_test)
plt.plot(x_test,y_test_predict,color='g',marker='*')
plt.show()